# Generated by Django 3.2.13 on 2022-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stargazer',
            fields=[
                ('id', models.PositiveIntegerField(help_text='GitHub user ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='GitHub username', max_length=200, unique=True)),
                ('url', models.URLField(help_text='GitHub user profile URL')),
                ('avatar', models.URLField(help_text='GitHub user avatar URL')),
            ],
            options={
                'verbose_name': 'Stargazer',
                'verbose_name_plural': 'Stargazers',
                'ordering': ('name',),
            },
        ),
    ]
