# Generated by Django 3.2.13 on 2022-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, help_text='Version of the release', max_length=16)),
                ('url', models.URLField(help_text='URL of the release')),
                ('published', models.DateTimeField(db_index=True, help_text='Date and time of the release')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ('-published',),
            },
        ),
    ]
